data:
  real_dir_path: [
  "trained_models/real_0/ckpt.pth",
  "trained_models/real_1/ckpt.pth",
  ]
  fake_dir_path: [
  "trained_models/fake_0/ckpt.pth",
  "trained_models/fake_1/ckpt.pth",
  ]


logging:
  log_metrics: True
  existing_experiment_id: "" # specify if you want to continue certain neptune experiment
  name: "GMMs"
  description: ""
  tags: []
  api_token_name: neptune_api_token
